name: Tony Lobl
favicon: null
layout_spectrum: 0.6835310368333012
typography_spectrum: 0.011940686032176018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23083810484968126
  lightness: 0.05057340953499079
  saturation: 0.08661129442043602
  rhythmicContrast: 0.618295201798901
purpose: []
